### ISSUE TITLE
[Ignore] Understanding the different markup

### ISSUE THREAD

**Issue by carpii** [russss/barclayscrape#40]
Ignore this issue, I'm just using it as a scratchboard to record the vastly different markup people are reporting

If you're having an issue with logging in via this library, feel free to post here using the following template...

````
Account Type: Business/Personal/Both
Passcode Enabled: Yes/No
PinSentry Enabled: Yes/No
Mobile PINSentry Enabled: Yes/No
 
### Step 2 Images...
````

Don't post other comments or discussion here please, use #39 instead

**Comment by carpii** [comment]
From @carpii 

Account Type:				Personal
Passcode:			Yes
PinSentry: 				Yes
Mobile PINSentry:			No

### Step 2 screenshots

![](https://i.imgur.com/e7rykUa.png)

![](https://i.imgur.com/3Wgthm4.png)

**Comment by carpii** [comment]
From @russss 

Account Type: Personal (?)
Passcode: No
PinSentry: Yes
Mobile PINSentry: Yes
 
### Step 2 Images...

![](https://i.imgur.com/8u3DpJc.png)

**Comment by carpii** [comment]
From @CharlesButcher

**Comment by jimfrench** [comment]
Hi @carpii 
I realise the timing of this is impeccable - however I had a few hours today to have a look at your debugging branch, and have had some success. I realise you said not to post on this issue but I thought it would directly relate to what you are collating above.

Account type: Personal, business, loan
Passcode: No, but optional, can be switched on and off in settings
PinSentry: yes
Smartcard reader: yes
Mobile pinsentry: yes

Firstly your post directly before this reply, is I think one of the issues. CharlesButcher and I have both managed to get this screen, where it asks to choose authentication method. I was not getting this option initially, but I managed to turn it back on in Barclays settings. Therefore, I think Charles and I are repeating the same bug, I have now managed to run your debug tests as follows. I hope this helps.

`Debug Log:

2020-06-26T23:09:51 -- Load URL                about:blank --> https://bank.barclays.co.uk
2020-06-26T23:09:54 -- wait OK                 https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification --> #membershipNum0
2020-06-26T23:09:54 -- Form key found          https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification --> #surname0
2020-06-26T23:09:56 -- Form key found          https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification --> #membershipNum0
2020-06-26T23:09:56 -- click                   https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification --> button[title="Next Step"]
2020-06-26T23:10:27 -- wait FAILED             https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/authentication --> button[title="Continue"]
2020-06-26T23:10:27 -- raise warning           https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/authentication --> action: fetching, selector: button[title="Continue"]
2020-06-26T23:10:27 -- Screenshot Dump         https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/authentication --> ./_debug_0.png
2020-06-26T23:10:27 -- HTML Dump               https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/authentication --> ./_debug_0.html.txt

> Dumping available radios
> Dumping available inputs
> Dumping available buttons
  Found button:  Text: ["Log in with PINsentry"], ID: [""]
  Found button:  Text: ["Log in with passcode"], ID: [""]

Call Stack:

TimeoutError: waiting for selector "button[title="Continue"]" failed: timeout 30000ms exceeded
    at new WaitTask (/home/jim/barclays_debug/node_modules/puppeteer/lib/DOMWorld.js:561:28)
    at DOMWorld._waitForSelectorOrXPath (/home/jim/barclays_debug/node_modules/puppeteer/lib/DOMWorld.js:490:22)
    at DOMWorld.waitForSelector (/home/jim/barclays_debug/node_modules/puppeteer/lib/DOMWorld.js:444:17)
    at Frame.waitForSelector (/home/jim/barclays_debug/node_modules/puppeteer/lib/FrameManager.js:628:47)
    at Frame.<anonymous> (/home/jim/barclays_debug/node_modules/puppeteer/lib/helper.js:112:23)
    at Frame.waitFor (/home/jim/barclays_debug/node_modules/puppeteer/lib/FrameManager.js:613:19)
    at Page.waitFor (/home/jim/barclays_debug/node_modules/puppeteer/lib/Page.js:1080:29)
    at Object.exports.wait (/home/jim/barclays_debug/utils.js:115:16)
    at Session.loginSelectMethod (/home/jim/barclays_debug/session.js:42:13)
    at Session.loginMOTP (/home/jim/barclays_debug/session.js:84:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/jim/barclays_debug/node_modules/puppeteer/lib/helper.js:111:15)
    at Frame.waitFor (/home/jim/barclays_debug/node_modules/puppeteer/lib/FrameManager.js:613:19)
    at Page.waitFor (/home/jim/barclays_debug/node_modules/puppeteer/lib/Page.js:1080:29)
    at Object.exports.wait (/home/jim/barclays_debug/utils.js:115:16)
    at Session.loginSelectMethod (/home/jim/barclays_debug/session.js:42:13)
    at Session.loginMOTP (/home/jim/barclays_debug/session.js:84:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
--------------------
Couldn't find selector button[title="Continue"] on page https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/authentication.
jim@ibase:~/barclays_debug$ 
`

**Comment by jimfrench** [comment]
![_debug_0](https://user-images.githubusercontent.com/19787762/85908417-db80ef80-b80c-11ea-9148-3a95dd4e37a8.png)

**Comment by jimfrench** [comment]
![_debug_0](https://user-images.githubusercontent.com/19787762/85908444-ffdccc00-b80c-11ea-9cb8-9ecc1f7f30ae.png)

**Comment by carpii** [comment]
Hi @jimfrench,

Thanks, this is really useful. The markup errors you are seeing pretty much align with what I was expecting
But since you are now able to run my repo, it makes fixing the issue so much easier.

Give me a few days and I'll push a new version which tries to bypass this interim page 
After that it may just work, or it may throw up other errors we need to address

**Comment by jimfrench** [comment]
Hi @carpii 
Thanks I'm pleased to be able to to help and feel I can do more now also . I did save a log of what I was doing. It includes the setup of the library from the beginning, I have gone through the log and removed sensitive details and also cut out meaningless errors etc while working. I hope it makes sense and is useful for the extra information there.

I was thinking about his last night, I do feel my Barclays account is capable of a lot of testing, e.g. creating flow chart of the different options, or I write in pseudocode what each authentication chain gives with regard to the different prompts, with screen grabs etc.

I do not know enough about the languages you are working in to directly attempt debugging but here and willing to help as much as possible to try to get it up and running for each different possible configuration :) 

By the way you're looking at a clean installation of Xubuntu desktop - I did not have to do anything funky to get the library up and running, aside from carefully following all original instructions given in the original README . There were a few minor issues which I cut out from the log, but I don't think there are any Python related issues going on, as long as everything is up to date and carefully in place. I did not have to apply any patches to node modules or anything of that sort.

I think the installation errors that @CharlesButcher was facing is down to the possible oddities of running it in MacOS. Unfortunately that ecosystem is very much not my area I don't use macs so unable to repeat what he was going through. He did seem to resolve those issues in part and get the library running though, because he reached the same eventual library error as I am now so that is promising.


[barclays_debug_log_ibase_20200626_1.txt](https://github.com/russss/barclayscrape/files/4840350/barclays_debug_log_ibase_20200626_1.txt)

**Comment by CharlesButcher** [comment]
Just for the record…

Account Type: Business
Passcode Enabled: Yes
PinSentry Enabled: Yes
Mobile PINSentry Enabled: Yes

![Barclays_1](https://user-images.githubusercontent.com/8853681/86016825-3425d780-ba1b-11ea-84db-0b4f04c3d554.png)
![Barclays_2](https://user-images.githubusercontent.com/8853681/86016839-3720c800-ba1b-11ea-811a-3fa7e1d1cb69.png)
![Barclays_3](https://user-images.githubusercontent.com/8853681/86016843-37b95e80-ba1b-11ea-82eb-89f5a6d896fa.png)

Good to hear that @jimfrench has had some success with this, and I'm sorry my own setup has got messy. I'm not convinced that macOS has much to do with this; I think it's more to do with my own inexperience in managing node versions and modules, and subsequently python. The fact that Apple's built-in python is well out of date is definitely a pain, but I did have barclayscrape working at one point, in the sense that it only failed when it met unexpected HTML on the Barclays website. At some point I'll be up for clearing everything out and starting from scratch.

**Comment by carpii** [comment]
Hi @jimfrench 

I've pushed a couple of updates to my debug branch 
If you could pull those changes and give it another test, and post the debug output if it's still failing?

Thanks

**Comment by jimfrench** [comment]
Hi @carpii 
Thanks for continuing to work on this, unfortunately it looks like the same or very similar debug output as enclosed.

I double checked I was pulling your most recent changes.

[barclays_debug_log_ibase_20200709_1.txt](https://github.com/russss/barclayscrape/files/4898350/barclays_debug_log_ibase_20200709_1.txt)

**Comment by carpii** [comment]
Thanks @jimfrench 

This is actually progress. I wasn't expecting it to work just yet, but I can continue with more changes. Will post another update when I can

**Comment by jimfrench** [comment]
@carpii OK brilliant I'll try to respond to tests as quickly as possible.
 =
I wonder if @CharlesButcher  is able to run the test ?

**Comment by jimfrench** [comment]
@carpii  OK brilliant I'll try to respond to tests as quickly as possible.

I wonder if @CharlesButcher is able to run the test ?

**Comment by carpii** [comment]
Not sure, but it's likely to show the same results

**Comment by carpii** [comment]
Abandoning ticket, sorry guys

I was hopeful I could get this working, but without having a Barclays account configured in the exact same way as yours, it's proven very difficult to figure out how to automate it
