### ISSUE TITLE
Mobile PINSentry not being selected during login

### ISSUE THREAD

**Issue by ryanwwhittaker** [russss/barclayscrape#49]
Hi,
I'm trying to connect using 'motp' however during login (and when showing browser - ie. no-headless) I can see that the Mobile PINSentry tab is not being selected on the screen that appears after the initial screen.  I am supplying my surname and membership no. in that first screen.
Running this on a Mac and opening in Chromium.
Launching in terminal within VS Code.

Here is the trace in terminal:
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/Users/ryan/VSCode/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:329:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ElementHandle.click (/Users/ryan/VSCode/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:390:26)
    at async DOMWorld.click (/Users/ryan/VSCode/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:9)
    at async Object.exports.fillFields (/Users/ryan/VSCode/barclayscrape/node_modules/barclayscrape/utils.js:33:5)
    at async Session.loginMOTP (/Users/ryan/VSCode/barclayscrape/node_modules/barclayscrape/session.js:65:5)
    at async auth (/Users/ryan/VSCode/barclayscrape/node_modules/barclayscrape/barclayscrape.js:222:5)
    at async Command.<anonymous> (/Users/ryan/VSCode/barclayscrape/node_modules/barclayscrape/barclayscrape.js:30:14)

Any ideas?

Thanks
Ryan

**Comment by carpii** [comment]
Are you a new user, or was this working for you previously and has suddenly stopped working?

**Comment by carpii** [comment]
@ryanwwhittaker I cant reproduce the error you're seeing, although I did get a different error earlier (due to Barclays showing a fraud scam interim page).

Are you seeing this error every time, or intermittently?

Does your Barclays login have a mix of Personal and Business accounts?

**Comment by ryanwwhittaker** [comment]
I am seeing this issue every time I try.
I only have Personal accounts (some are Joint accounts).

I wonder if something not quite right with Puppeteer or Chromium.

**Comment by carpii** [comment]
The line numbers in the error message suggest you might not be using the latest version. Make sure your git branch is fully up to date as there were some changes in February to handle the tab selection

**Comment by russss** [comment]
Oh, I forgot to publish those changes to npm. I've now done so (version 3.0.17), so make sure you're using that if you're installing the package.

**Comment by ryanwwhittaker** [comment]
Looks like the publishing did the trick and I could now download statements.
Thanks
