### ISSUE TITLE
New login page layer (aka No node found for selector: #lastDigits0)

### ISSUE THREAD

**Issue by castaway** [russss/barclayscrape#53]
Looks like we need to add something to click on the "PINsentry card reader" tab

![2022-10-18 14 47 15 bank barclays co uk 9f1bf2c65423](https://user-images.githubusercontent.com/109990/196448079-98e18fc2-ada1-4c6f-900c-9a99b8bbc15d.jpg)

Happy to have a go later (if I can figure out the code..)

**Comment by carpii** [comment]
Whats the ID of the 'The Barclays App' tab?

`loginSelectMethod` in session.js, already attempts to click the correct tab

**Comment by castaway** [comment]
Ah, I've never seen it while manually logging in.

`<button id="athenticationType_tab_button_0"`

```
Error: No node found for selector: #lastDigits0
    at assert (/mnt/allthespace/usrsrc/extern/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/mnt/allthespace/usrsrc/extern/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:285:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.fillField (/mnt/allthespace/usrsrc/extern/barclayscrape/utils.js:34:5)
    at async exports.fillFields (/mnt/allthespace/usrsrc/extern/barclayscrape/utils.js:41:5)
    at async Session.loginOTP (/mnt/allthespace/usrsrc/extern/barclayscrape/session.js:65:5)
    at async auth (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:272:7)
    at async Command.<anonymous> (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:86:14)

```

**Comment by castaway** [comment]
Hmm, looking at my copy of session.js, that seems to matcjh

**Comment by carpii** [comment]
As far as I can tell, they have started randomising the ID of the `Enter the last 4 digits of your card` input, instead of it always being called `lastDigits0`.

I'll see if I can come up with something

**Comment by carpii** [comment]
Could you try changing `session.js:loginOTP()` from

`'#lastDigits0': credentials['card_digits'],`

to 

`'input[name="lastDigits"]': credentials['card_digits'],`

**Comment by castaway** [comment]
sneaky, yup that works (worked once at least ;)

**Comment by carpii** [comment]
ok, I'll submit a pull request

**Comment by castaway** [comment]
That lasted well :(
`Error: No node found for selector: input[name="lastDigits"]
    at assert (/mnt/allthespace/usrsrc/extern/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/mnt/allthespace/usrsrc/extern/barclayscrape/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:285:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.fillField (/mnt/allthespace/usrsrc/extern/barclayscrape/utils.js:34:5)
    at async exports.fillFields (/mnt/allthespace/usrsrc/extern/barclayscrape/utils.js:41:5)
    at async Session.loginOTP (/mnt/allthespace/usrsrc/extern/barclayscrape/session.js:65:5)
    at async auth (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:272:7)
    at async Command.<anonymous> (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:86:14)`

**Comment by castaway** [comment]
Hm, went to try manually definitely got that name, and worked when I ran barclayscrape again, maybe it just hiccuped?

**Comment by carpii** [comment]
I'm not sure what could cause that, but let me know if it happens again

I know Barclays do occasionally show an interim page (to announce maintenance, or warn about ongoing scams). This sometimes causes scraper to bork, but running it again is fine.

I'm trying to add improvements to bypass these interim pages, but it's slow progress as they are only ever shown once and then that's it.

**Comment by carpii** [comment]
@castaway have you had any further problems with this? If not, could you close the ticket?

Thanks

**Comment by castaway** [comment]
Not so far!
